#!/bin/bash

read -p "Enter a number: " NUMBER
NUMBER=`echo $NUMBER | tr -d [:punct:] | tr -d [:alpha:]`

if [ "$NUMBER" -gt 10 ]; then
    echo "$NUMBER is larger than 10."
elif [ "$NUMBER" -eq 10 ]; then
    echo "$NUMBER is equal to 10."
else
    echo "$NUMBER is smaller than 10"
fi
